DROP TABLE IF EXISTS Schedule;


CREATE TABLE Schedule (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    emp_name TEXT,
    monday TEXT,
    tuesday TEXT,
    wednesday TEXT,
    thursday TEXT,
    friday TEXT,
    saturday TEXT,
    sunday TEXT
);


